### ISSUE TITLE
Portfolio name being read as guest name

### ISSUE THREAD

**Issue by Chang-CH** [Colon-WQ/Portfolio#114]
![image](https://user-images.githubusercontent.com/37036869/123550742-9a197c00-d7a1-11eb-810d-afe1a94f52de.png)
### Steps to replicate

1. Enter dashboard without logging in
2. Create a portfolio
3. navigate back to /dashboard

### Notes
- MongoDB was not running in this instance. An invalid mongo URL was passed to mongoose

**Comment by twothicc** [comment]
- Issue is because previously, the localStorage object either has the user object or it does not, indicating whether use is logged in or not.

- However, with recent changes made to allow Guest user, loggedIn boolean in user object actually matters more beyond just indicating to home page to send a request for gh code to login the user.

- This means that user object can exist in localStorage without the user being logged in (loggedIn boolean is false). LoginResult was not updated to handle this change yet. LoginResult simply checked if you have the user object, which you do, and sent you straight to dashboard without logging in. 

- The odd thing would be that the name in your localStorage persisted from before as "MyPortfolio".

- New Push should fix this by checking for the loggedIn boolean after retrieving the user object from localStorage. If false, it will login the user and set the user object accordingly. If true, user gets sent to dashboard.
- There should be no security issues with this approach. If the user does not login, the session on the database will simply not exist and any operations will simply fail and send the user back to home page.
