### ISSUE TITLE
Unexpected background change on clicking login as guest

### ISSUE THREAD

**Issue by Chang-CH** [Colon-WQ/Portfolio#134]
### Description
clicking on login as guest on homepage seems to shift the background image in the root div
![image](https://user-images.githubusercontent.com/37036869/124239569-6c8b5480-db4c-11eb-9254-c4b0f6b3e80c.png)
![image](https://user-images.githubusercontent.com/37036869/124239610-78771680-db4c-11eb-8aeb-a636ad4b4615.png)

Problem seems to be similar to the jss issue with inline styling, Body is having state changes
![image](https://user-images.githubusercontent.com/37036869/124239846-b4aa7700-db4c-11eb-86c1-62c3c2930f9c.png)
![image](https://user-images.githubusercontent.com/37036869/124239800-a9efe200-db4c-11eb-86e8-1b0bc156523a.png)

**Comment by twothicc** [comment]
- When the dialog opens, the scroll bar disappears because scrolling is disabled. However, due to this paddingRight is automatically added to the body styles to account for the loss of scroll bar due to dialog opening.
- Fixed temporarily by adding "disabledScrollLock" to dialog component.
- Downside to this is that scrolling is now possible when dialog shows.
- https://github.com/mui-org/material-ui/issues/10000
