### ISSUE TITLE
401 error message in dashboard

### ISSUE THREAD

**Issue by Chang-CH** [Colon-WQ/Portfolio#135]
### Steps to replicate

1. Clear site data, such that get started routes to login callback
2. Login via github, wait for token/session to expire*
3. Visit home page
4. Home button should be "To Dashboard"
5. On clicking to dashboard, dashboard will have a 401 status code

*exact steps unknown. Did not logout but closed the server, after one night steps 3-5 caused the error

Clearing site data and reloading fixes the issue, so problem might lie in:

1. refresh token expired but login state still causes to dashboard to appear in homepage
2. Github token is expired but login state/refresh token are still valid

**Comment by twothicc** [comment]
- session in mongoDB expires in 6hrs.
- The cookie with the session _id lasts indefinitely. Since you left it overnight, the session most likely expired and will be automatically removed from database.
- 401 status code is the intended response, since your session _id points to a session that has already expired and is therefore non-existent. However, the error handling should have redirected you to home page. Is that the case?

**Comment by Chang-CH** [comment]
error handling did not redirect to home page. Home page was to dashboard before clicking, typography in dashboard showed 401 afterwards but nothing else happens.

**Comment by twothicc** [comment]
- The fetch function for portfolios was not updated and did not use the standard error handler. Fixed.
